import type { Question } from "./types";

/** A small lecturer-written set the teacher can load onto an empty bank. */
export const STARTER_LECTURER: Omit<Question, "id">[] = [
  {
    stage: "little",
    section: "objective",
    prompt: "What did God make on the first day?",
    options: ["Light", "Animals", "People", "The sea"],
    answer: "Light",
    aliases: ["the light"],
    reference: "Genesis 1:3",
    source: "lecturer",
    published: true,
  },
  {
    stage: "little",
    section: "blank",
    prompt: "God said, Let there be ______.",
    options: [],
    answer: "light",
    aliases: ["the light"],
    reference: "Genesis 1:3",
    source: "lecturer",
    published: true,
  },
  {
    stage: "growing",
    section: "objective",
    prompt: "How many days and nights was Jonah in the great fish?",
    options: ["Three", "Seven", "Forty", "Twelve"],
    answer: "Three",
    aliases: ["3", "three days"],
    reference: "Jonah 1:17",
    source: "lecturer",
    published: true,
  },
  {
    stage: "growing",
    section: "blank",
    prompt: "The Lord is my ______; I shall not want.",
    options: [],
    answer: "shepherd",
    aliases: ["the shepherd"],
    reference: "Psalm 23:1",
    source: "lecturer",
    published: true,
  },
  {
    stage: "juniors",
    section: "objective",
    prompt: "Which book comes first in the New Testament?",
    options: ["Matthew", "Genesis", "Acts", "Psalms"],
    answer: "Matthew",
    aliases: ["the gospel of matthew"],
    reference: "NT order",
    source: "lecturer",
    published: true,
  },
  {
    stage: "juniors",
    section: "blank",
    prompt: "Your word is a lamp to my ______.",
    options: [],
    answer: "feet",
    aliases: ["foot"],
    reference: "Psalm 119:105",
    source: "lecturer",
    published: true,
  },
  {
    stage: "youth",
    section: "objective",
    prompt: "Who wrote many of the New Testament letters to the churches?",
    options: ["Paul", "Moses", "David", "Abraham"],
    answer: "Paul",
    aliases: ["the apostle paul", "saul", "st paul"],
    reference: "Epistles",
    source: "lecturer",
    published: true,
  },
  {
    stage: "youth",
    section: "blank",
    prompt: "In the beginning was the ______.",
    options: [],
    answer: "Word",
    aliases: ["the word", "logos"],
    reference: "John 1:1",
    source: "lecturer",
    published: true,
  },
  {
    stage: "general",
    section: "objective",
    prompt: "How many books are in the Protestant Bible?",
    options: ["66", "40", "12", "100"],
    answer: "66",
    aliases: ["sixty-six", "sixty six"],
    reference: "Canon",
    source: "lecturer",
    published: true,
  },
  {
    stage: "general",
    section: "blank",
    prompt: "The fruit of the Spirit includes love, joy, and ______.",
    options: [],
    answer: "peace",
    aliases: [],
    reference: "Galatians 5:22",
    source: "lecturer",
    published: true,
  },
];
