/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoardRouteImport } from './routes/board'
import { Route as DoneRouteImport } from './routes/done'
import { Route as HallRouteImport } from './routes/hall'
import { Route as NotebookRouteImport } from './routes/notebook'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as VerseRouteImport } from './routes/verse'
import { Route as CardsIndexRouteImport } from './routes/cards.index'
import { Route as CardsStageIdRouteImport } from './routes/cards.$stageId'
import { Route as CertificatePaperIdRouteImport } from './routes/certificate.$paperId'
import { Route as ExamStageIdRouteImport } from './routes/exam.$stageId'
import { Route as PracticeStageIdRouteImport } from './routes/practice.$stageId'
import { Route as ReviewPaperIdRouteImport } from './routes/review.$paperId'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as TeacherBankRouteImport } from './routes/teacher.bank'
import { Route as TeacherResultsRouteImport } from './routes/teacher.results'
import { Route as TeacherKeysStageIdRouteImport } from './routes/teacher.keys.$stageId'
import { Route as TeacherPaperPaperIdRouteImport } from './routes/teacher.paper.$paperId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const DoneRoute = DoneRouteImport.update({
  id: '/done',
  path: '/done',
  getParentRoute: () => rootRouteImport,
} as any)
const HallRoute = HallRouteImport.update({
  id: '/hall',
  path: '/hall',
  getParentRoute: () => rootRouteImport,
} as any)
const NotebookRoute = NotebookRouteImport.update({
  id: '/notebook',
  path: '/notebook',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const VerseRoute = VerseRouteImport.update({
  id: '/verse',
  path: '/verse',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsIndexRoute = CardsIndexRouteImport.update({
  id: '/cards/',
  path: '/cards/',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsStageIdRoute = CardsStageIdRouteImport.update({
  id: '/cards/$stageId',
  path: '/cards/$stageId',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatePaperIdRoute = CertificatePaperIdRouteImport.update({
  id: '/certificate/$paperId',
  path: '/certificate/$paperId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamStageIdRoute = ExamStageIdRouteImport.update({
  id: '/exam/$stageId',
  path: '/exam/$stageId',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeStageIdRoute = PracticeStageIdRouteImport.update({
  id: '/practice/$stageId',
  path: '/practice/$stageId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewPaperIdRoute = ReviewPaperIdRouteImport.update({
  id: '/review/$paperId',
  path: '/review/$paperId',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherBankRoute = TeacherBankRouteImport.update({
  id: '/bank',
  path: '/bank',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherResultsRoute = TeacherResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherKeysStageIdRoute = TeacherKeysStageIdRouteImport.update({
  id: '/keys/$stageId',
  path: '/keys/$stageId',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherPaperPaperIdRoute = TeacherPaperPaperIdRouteImport.update({
  id: '/paper/$paperId',
  path: '/paper/$paperId',
  getParentRoute: () => TeacherRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/board': typeof BoardRoute
  '/done': typeof DoneRoute
  '/hall': typeof HallRoute
  '/notebook': typeof NotebookRoute
  '/progress': typeof ProgressRoute
  '/teacher': typeof TeacherRouteWithChildren
  '/verse': typeof VerseRoute
  '/cards/$stageId': typeof CardsStageIdRoute
  '/certificate/$paperId': typeof CertificatePaperIdRoute
  '/exam/$stageId': typeof ExamStageIdRoute
  '/practice/$stageId': typeof PracticeStageIdRoute
  '/review/$paperId': typeof ReviewPaperIdRoute
  '/teacher/bank': typeof TeacherBankRoute
  '/teacher/results': typeof TeacherResultsRoute
  '/cards/': typeof CardsIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/teacher/keys/$stageId': typeof TeacherKeysStageIdRoute
  '/teacher/paper/$paperId': typeof TeacherPaperPaperIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/board': typeof BoardRoute
  '/done': typeof DoneRoute
  '/hall': typeof HallRoute
  '/notebook': typeof NotebookRoute
  '/progress': typeof ProgressRoute
  '/verse': typeof VerseRoute
  '/cards/$stageId': typeof CardsStageIdRoute
  '/certificate/$paperId': typeof CertificatePaperIdRoute
  '/exam/$stageId': typeof ExamStageIdRoute
  '/practice/$stageId': typeof PracticeStageIdRoute
  '/review/$paperId': typeof ReviewPaperIdRoute
  '/teacher/bank': typeof TeacherBankRoute
  '/teacher/results': typeof TeacherResultsRoute
  '/cards': typeof CardsIndexRoute
  '/teacher': typeof TeacherIndexRoute
  '/teacher/keys/$stageId': typeof TeacherKeysStageIdRoute
  '/teacher/paper/$paperId': typeof TeacherPaperPaperIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/board': typeof BoardRoute
  '/done': typeof DoneRoute
  '/hall': typeof HallRoute
  '/notebook': typeof NotebookRoute
  '/progress': typeof ProgressRoute
  '/teacher': typeof TeacherRouteWithChildren
  '/verse': typeof VerseRoute
  '/cards/$stageId': typeof CardsStageIdRoute
  '/certificate/$paperId': typeof CertificatePaperIdRoute
  '/exam/$stageId': typeof ExamStageIdRoute
  '/practice/$stageId': typeof PracticeStageIdRoute
  '/review/$paperId': typeof ReviewPaperIdRoute
  '/teacher/bank': typeof TeacherBankRoute
  '/teacher/results': typeof TeacherResultsRoute
  '/cards/': typeof CardsIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/teacher/keys/$stageId': typeof TeacherKeysStageIdRoute
  '/teacher/paper/$paperId': typeof TeacherPaperPaperIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/board'
    | '/done'
    | '/hall'
    | '/notebook'
    | '/progress'
    | '/teacher'
    | '/verse'
    | '/cards/$stageId'
    | '/certificate/$paperId'
    | '/exam/$stageId'
    | '/practice/$stageId'
    | '/review/$paperId'
    | '/teacher/bank'
    | '/teacher/results'
    | '/cards/'
    | '/teacher/'
    | '/teacher/keys/$stageId'
    | '/teacher/paper/$paperId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/board'
    | '/done'
    | '/hall'
    | '/notebook'
    | '/progress'
    | '/verse'
    | '/cards/$stageId'
    | '/certificate/$paperId'
    | '/exam/$stageId'
    | '/practice/$stageId'
    | '/review/$paperId'
    | '/teacher/bank'
    | '/teacher/results'
    | '/cards'
    | '/teacher'
    | '/teacher/keys/$stageId'
    | '/teacher/paper/$paperId'
  id:
    | '__root__'
    | '/'
    | '/board'
    | '/done'
    | '/hall'
    | '/notebook'
    | '/progress'
    | '/teacher'
    | '/verse'
    | '/cards/$stageId'
    | '/certificate/$paperId'
    | '/exam/$stageId'
    | '/practice/$stageId'
    | '/review/$paperId'
    | '/teacher/bank'
    | '/teacher/results'
    | '/cards/'
    | '/teacher/'
    | '/teacher/keys/$stageId'
    | '/teacher/paper/$paperId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoardRoute: typeof BoardRoute
  DoneRoute: typeof DoneRoute
  HallRoute: typeof HallRoute
  NotebookRoute: typeof NotebookRoute
  ProgressRoute: typeof ProgressRoute
  TeacherRoute: typeof TeacherRouteWithChildren
  VerseRoute: typeof VerseRoute
  CardsStageIdRoute: typeof CardsStageIdRoute
  CertificatePaperIdRoute: typeof CertificatePaperIdRoute
  ExamStageIdRoute: typeof ExamStageIdRoute
  PracticeStageIdRoute: typeof PracticeStageIdRoute
  ReviewPaperIdRoute: typeof ReviewPaperIdRoute
  CardsIndexRoute: typeof CardsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/done': {
      id: '/done'
      path: '/done'
      fullPath: '/done'
      preLoaderRoute: typeof DoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hall': {
      id: '/hall'
      path: '/hall'
      fullPath: '/hall'
      preLoaderRoute: typeof HallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notebook': {
      id: '/notebook'
      path: '/notebook'
      fullPath: '/notebook'
      preLoaderRoute: typeof NotebookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verse': {
      id: '/verse'
      path: '/verse'
      fullPath: '/verse'
      preLoaderRoute: typeof VerseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards/': {
      id: '/cards/'
      path: '/cards'
      fullPath: '/cards/'
      preLoaderRoute: typeof CardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards/$stageId': {
      id: '/cards/$stageId'
      path: '/cards/$stageId'
      fullPath: '/cards/$stageId'
      preLoaderRoute: typeof CardsStageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificate/$paperId': {
      id: '/certificate/$paperId'
      path: '/certificate/$paperId'
      fullPath: '/certificate/$paperId'
      preLoaderRoute: typeof CertificatePaperIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/$stageId': {
      id: '/exam/$stageId'
      path: '/exam/$stageId'
      fullPath: '/exam/$stageId'
      preLoaderRoute: typeof ExamStageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/$stageId': {
      id: '/practice/$stageId'
      path: '/practice/$stageId'
      fullPath: '/practice/$stageId'
      preLoaderRoute: typeof PracticeStageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/$paperId': {
      id: '/review/$paperId'
      path: '/review/$paperId'
      fullPath: '/review/$paperId'
      preLoaderRoute: typeof ReviewPaperIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/bank': {
      id: '/teacher/bank'
      path: '/bank'
      fullPath: '/teacher/bank'
      preLoaderRoute: typeof TeacherBankRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/results': {
      id: '/teacher/results'
      path: '/results'
      fullPath: '/teacher/results'
      preLoaderRoute: typeof TeacherResultsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/keys/$stageId': {
      id: '/teacher/keys/$stageId'
      path: '/keys/$stageId'
      fullPath: '/teacher/keys/$stageId'
      preLoaderRoute: typeof TeacherKeysStageIdRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/paper/$paperId': {
      id: '/teacher/paper/$paperId'
      path: '/paper/$paperId'
      fullPath: '/teacher/paper/$paperId'
      preLoaderRoute: typeof TeacherPaperPaperIdRouteImport
      parentRoute: typeof TeacherRoute
    }
  }
}

interface TeacherRouteChildren {
  TeacherBankRoute: typeof TeacherBankRoute
  TeacherResultsRoute: typeof TeacherResultsRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
  TeacherKeysStageIdRoute: typeof TeacherKeysStageIdRoute
  TeacherPaperPaperIdRoute: typeof TeacherPaperPaperIdRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherBankRoute: TeacherBankRoute,
  TeacherResultsRoute: TeacherResultsRoute,
  TeacherIndexRoute: TeacherIndexRoute,
  TeacherKeysStageIdRoute: TeacherKeysStageIdRoute,
  TeacherPaperPaperIdRoute: TeacherPaperPaperIdRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoardRoute: BoardRoute,
  DoneRoute: DoneRoute,
  HallRoute: HallRoute,
  NotebookRoute: NotebookRoute,
  ProgressRoute: ProgressRoute,
  TeacherRoute: TeacherRouteWithChildren,
  VerseRoute: VerseRoute,
  CardsStageIdRoute: CardsStageIdRoute,
  CertificatePaperIdRoute: CertificatePaperIdRoute,
  ExamStageIdRoute: ExamStageIdRoute,
  PracticeStageIdRoute: PracticeStageIdRoute,
  ReviewPaperIdRoute: ReviewPaperIdRoute,
  CardsIndexRoute: CardsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
